name: Build & Publish

on:
  push:
    branches:
      - "main"

jobs:
  next-build:
    runs-on: ubuntu-latest
    container: node:lts          # Use node LTS container version, same as Dockerfile base image
    steps:
      - name: Checkout
        uses: actions/checkout@v3       # Checkout the code
      - run: |
          npm install -g pnpm@6.14.5
          mkdir /app
          cd /app
          touch .env
          echo "${{ secrets.APPLICATION_ENV }}" > ./.env
          pnpm install
          pnpm run build
      - name: Upload Next build          # Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            .next
            public
          retention-days: 7      
  docker-push:
    needs: next-build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download next build  
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_HUB_KEY }}
          docker build -t sangdamplus-next-dev-image .
          docker tag sangdamplus-next-dev-image ${{ secrets.DOCKER_USERNAME }}/sangdamplus-next-dev-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sangdamplus-next-dev-image:latest
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: sangdam
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /data/sangdamplus/next-dev
            docker stop $(docker container ls -f "name=next-dev" -q)
            docker rm next-dev
            docker pull ${{ secrets.DOCKER_USERNAME }}/sangdamplus-next-dev-image:latest
            docker run -d --name next-dev --network sangdam --log-driver=syslog -p 10100:3000 ${{ secrets.DOCKER_USERNAME }}/sangdamplus-next-dev-image
            docker image prune -a -f